INFO: 2021-07-19 16:58:10,718: main() 'Using profile folder /home/ravanla/.config/variety/'
INFO: 2021-07-19 16:58:10,725: perform_upgrade() 'Last run version was 0.8.5 or earlier, current version is 0.8.5'
INFO: 2021-07-19 16:58:11,109: process_command() 'Received command: []'
INFO: 2021-07-19 16:58:11,112: load_banned() 'Missing or invalid banned URLs list, no URLs will be banned'
INFO: 2021-07-19 16:58:11,128: start() 'Using data_path /usr/share/variety'
INFO: 2021-07-19 16:58:11,128: load() 'Jumble loading'
INFO: 2021-07-19 16:58:11,129: _walk_modules() 'Jumble loading module in __init__ from /usr/lib/python3.9/site-packages/variety/plugins/builtin/__init__.py'
INFO: 2021-07-19 16:58:11,134: _walk_modules() 'Jumble loading module in __init__ from /usr/lib/python3.9/site-packages/variety/plugins/builtin/quotes/__init__.py'
INFO: 2021-07-19 16:58:11,135: _walk_modules() 'Jumble loading module in QuotationsPageSource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/quotes/QuotationsPageSource.py'
INFO: 2021-07-19 16:58:11,147: load() 'Jumble found plugin class: <class 'QuotationsPageSource.QuotationsPageSource'>: {'name': 'TheQuotationsPage.com', 'description': 'Fetches quotes from TheQuotationsPage.com', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-07-19 16:58:11,148: _walk_modules() 'Jumble loading module in GoodreadsSource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/quotes/GoodreadsSource.py'
INFO: 2021-07-19 16:58:11,149: load() 'Jumble found plugin class: <class 'GoodreadsSource.GoodreadsSource'>: {'name': 'Goodreads', 'description': 'Fetches quotes from Goodreads.com', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-07-19 16:58:11,150: _walk_modules() 'Jumble loading module in LocalFilesSource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/quotes/LocalFilesSource.py'
INFO: 2021-07-19 16:58:11,151: load() 'Jumble found plugin class: <class 'LocalFilesSource.LocalFilesSource'>: {'name': 'Local text files', 'description': 'Displays quotes, defined in local text files.\nPut your own txt files in: ~/.config/variety/pluginconfig/quotes/.\nThe file format is:\n\nquote -- author\n.\nsecond quote -- another author\n.\netc...\n\nExample: http://rvelthuis.de/zips/quotes.txt', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-07-19 16:58:11,152: _walk_modules() 'Jumble loading module in FortuneSource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/quotes/FortuneSource.py'
INFO: 2021-07-19 16:58:11,154: load() 'Jumble found plugin class: <class 'FortuneSource.FortuneSource'>: {'name': 'UNIX fortune program', 'description': 'Displays quotes using the UNIX fortune program. You may want to install additional fortune packs, e.g. fortunes-bofh-excuses.', 'author': 'Dan Jones', 'version': '0.1'}'
INFO: 2021-07-19 16:58:11,155: _walk_modules() 'Jumble loading module in UrbanDictionarySource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/quotes/UrbanDictionarySource.py'
INFO: 2021-07-19 16:58:11,157: load() 'Jumble found plugin class: <class 'UrbanDictionarySource.UrbanDictionarySource'>: {'name': 'Urban Dictionary', 'description': 'Displays definitions from Urban Dictionary', 'author': 'James Miller', 'version': '0.1'}'
INFO: 2021-07-19 16:58:11,158: _walk_modules() 'Jumble loading module in WallhavenDownloader from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/WallhavenDownloader.py'
INFO: 2021-07-19 16:58:11,160: _walk_modules() 'Jumble loading module in MediaRSSDownloader from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/MediaRSSDownloader.py'
INFO: 2021-07-19 16:58:11,161: _walk_modules() 'Jumble loading module in __init__ from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/__init__.py'
INFO: 2021-07-19 16:58:11,162: _walk_modules() 'Jumble loading module in UnsplashDownloader from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/UnsplashDownloader.py'
INFO: 2021-07-19 16:58:11,163: load() 'Jumble found plugin class: <class 'UnsplashDownloader.UnsplashDownloader'>: {'name': 'UnsplashDownloader', 'description': 'High-resolution photos from Unsplash.com', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-07-19 16:58:11,164: _walk_modules() 'Jumble loading module in APODDownloader from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/APODDownloader.py'
INFO: 2021-07-19 16:58:11,165: load() 'Jumble found plugin class: <class 'APODDownloader.APODDownloader'>: {'name': 'APODDownloader', 'description': 'NASA Astro Pic of the Day', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-07-19 16:58:11,165: _walk_modules() 'Jumble loading module in UnsplashConfigurableSource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/UnsplashConfigurableSource.py'
INFO: 2021-07-19 16:58:11,168: load() 'Jumble found plugin class: <class 'UnsplashConfigurableSource.UnsplashConfigurableSource'>: {'name': 'UnsplashConfigurableSource', 'description': 'Configurable source for fetching photos from Unsplash.com', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-07-19 16:58:11,168: _walk_modules() 'Jumble loading module in RedditDownloader from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/RedditDownloader.py'
INFO: 2021-07-19 16:58:11,170: _walk_modules() 'Jumble loading module in WallhavenSource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/WallhavenSource.py'
INFO: 2021-07-19 16:58:11,171: load() 'Jumble found plugin class: <class 'WallhavenSource.WallhavenSource'>: {'name': 'WallhavenSource', 'description': 'Configurable source for fetching images from Wallhaven.cc', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-07-19 16:58:11,172: _walk_modules() 'Jumble loading module in BingDownloader from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/BingDownloader.py'
INFO: 2021-07-19 16:58:11,172: load() 'Jumble found plugin class: <class 'BingDownloader.BingDownloader'>: {'name': 'BingDownloader', 'description': 'Bing Photo of the Day', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-07-19 16:58:11,173: _walk_modules() 'Jumble loading module in RedditSource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/RedditSource.py'
INFO: 2021-07-19 16:58:11,174: load() 'Jumble found plugin class: <class 'RedditSource.RedditSource'>: {'name': 'RedditSource', 'description': 'Configurable source for fetching images from Reddit', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-07-19 16:58:11,174: _walk_modules() 'Jumble loading module in MediaRSSSource from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/MediaRSSSource.py'
INFO: 2021-07-19 16:58:11,175: load() 'Jumble found plugin class: <class 'MediaRSSSource.MediaRSSSource'>: {'name': 'MediaRSSSource', 'description': 'Configurable source for fetching images from MediaRSS feeds', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-07-19 16:58:11,176: _walk_modules() 'Jumble loading module in EarthviewDownloader from /usr/lib/python3.9/site-packages/variety/plugins/builtin/downloaders/EarthviewDownloader.py'
INFO: 2021-07-19 16:58:11,177: load() 'Jumble found plugin class: <class 'EarthviewDownloader.EarthviewDownloader'>: {'name': 'EarthviewDownloader', 'description': 'Google Earth View Wallpapers', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2021-07-19 16:58:11,184: log_options() 'Loaded options:'
INFO: 2021-07-19 16:58:11,185: log_options() 'change_enabled = False'
INFO: 2021-07-19 16:58:11,185: log_options() 'change_interval = 300'
INFO: 2021-07-19 16:58:11,185: log_options() 'change_on_start = False'
INFO: 2021-07-19 16:58:11,185: log_options() 'clipboard_enabled = False'
INFO: 2021-07-19 16:58:11,185: log_options() 'clipboard_hosts = ['wallhaven.cc', 'wallpapers.net', 'flickr.com', 'imgur.com', 'deviantart.com', 'interfacelift.com', 'vladstudio.com', 'imageshack.us', 'deviantart.net', 'imageshack.com']'
INFO: 2021-07-19 16:58:11,185: log_options() 'clipboard_use_whitelist = True'
INFO: 2021-07-19 16:58:11,185: log_options() 'clock_date_font = Ubuntu Condensed, 30'
INFO: 2021-07-19 16:58:11,185: log_options() 'clock_enabled = False'
INFO: 2021-07-19 16:58:11,185: log_options() 'clock_filter = -density 100 -font `fc-match -f '%{file[0]}' '%CLOCK_FONT_NAME'` -pointsize %CLOCK_FONT_SIZE -gravity SouthEast -fill '#00000044' -annotate 0x0+[%HOFFSET+58]+[%VOFFSET+108] '%H:%M' -fill white -annotate 0x0+[%HOFFSET+60]+[%VOFFSET+110] '%H:%M' -font `fc-match -f '%{file[0]}' '%DATE_FONT_NAME'` -pointsize %DATE_FONT_SIZE -fill '#00000044' -annotate 0x0+[%HOFFSET+58]+[%VOFFSET+58] '%A, %B %d' -fill white -annotate 0x0+[%HOFFSET+60]+[%VOFFSET+60] '%A, %B %d''
INFO: 2021-07-19 16:58:11,185: log_options() 'clock_font = Sans 70'
INFO: 2021-07-19 16:58:11,185: log_options() 'configfile = /home/ravanla/.config/variety/variety.conf'
INFO: 2021-07-19 16:58:11,186: log_options() 'copyto_enabled = False'
INFO: 2021-07-19 16:58:11,186: log_options() 'copyto_folder = Default'
INFO: 2021-07-19 16:58:11,186: log_options() 'desired_color = [160, 160, 160]'
INFO: 2021-07-19 16:58:11,186: log_options() 'desired_color_enabled = False'
INFO: 2021-07-19 16:58:11,187: log_options() 'download_folder = /home/ravanla/.config/variety/Downloaded'
INFO: 2021-07-19 16:58:11,187: log_options() 'download_preference_ratio = 0.9'
INFO: 2021-07-19 16:58:11,187: log_options() 'favorites_folder = /home/ravanla/.config/variety/Favorites'
INFO: 2021-07-19 16:58:11,187: log_options() 'favorites_operations = [['Downloaded', 'Copy'], ['Fetched', 'Move'], ['Others', 'Copy']]'
INFO: 2021-07-19 16:58:11,187: log_options() 'fetched_folder = /home/ravanla/.config/variety/Fetched'
INFO: 2021-07-19 16:58:11,187: log_options() 'filters = [[False, 'Keep original', ''], [False, 'Grayscale', '-type Grayscale'], [False, 'Heavy blur', '-blur 120x40'], [False, 'Soft blur', '-blur 20x7'], [False, 'Oil painting', '-paint 8'], [False, 'Pointilism', '-spread 10 -noise 3'], [False, 'Pixellate', '-scale 3% -scale 3333%']]'
INFO: 2021-07-19 16:58:11,187: log_options() 'icon = Dark'
INFO: 2021-07-19 16:58:11,187: log_options() 'lightness_enabled = False'
INFO: 2021-07-19 16:58:11,187: log_options() 'lightness_mode = 0'
INFO: 2021-07-19 16:58:11,187: log_options() 'min_rating = 4'
INFO: 2021-07-19 16:58:11,188: log_options() 'min_rating_enabled = False'
INFO: 2021-07-19 16:58:11,188: log_options() 'min_size = 80'
INFO: 2021-07-19 16:58:11,188: log_options() 'min_size_enabled = False'
INFO: 2021-07-19 16:58:11,188: log_options() 'quota_enabled = True'
INFO: 2021-07-19 16:58:11,188: log_options() 'quota_size = 1000'
INFO: 2021-07-19 16:58:11,188: log_options() 'quotes_authors = '
INFO: 2021-07-19 16:58:11,188: log_options() 'quotes_bg_color = [80, 80, 80]'
INFO: 2021-07-19 16:58:11,188: log_options() 'quotes_bg_opacity = 55'
INFO: 2021-07-19 16:58:11,188: log_options() 'quotes_change_enabled = False'
INFO: 2021-07-19 16:58:11,188: log_options() 'quotes_change_interval = 300'
INFO: 2021-07-19 16:58:11,188: log_options() 'quotes_disabled_sources = ['Urban Dictionary']'
INFO: 2021-07-19 16:58:11,188: log_options() 'quotes_enabled = False'
INFO: 2021-07-19 16:58:11,188: log_options() 'quotes_favorites_file = /home/ravanla/.config/variety/favorite_quotes.txt'
INFO: 2021-07-19 16:58:11,189: log_options() 'quotes_font = Bitstream Charter 30'
INFO: 2021-07-19 16:58:11,189: log_options() 'quotes_hpos = 100'
INFO: 2021-07-19 16:58:11,189: log_options() 'quotes_max_length = 250'
INFO: 2021-07-19 16:58:11,189: log_options() 'quotes_tags = '
INFO: 2021-07-19 16:58:11,189: log_options() 'quotes_text_color = [255, 255, 255]'
INFO: 2021-07-19 16:58:11,189: log_options() 'quotes_text_shadow = False'
INFO: 2021-07-19 16:58:11,189: log_options() 'quotes_vpos = 40'
INFO: 2021-07-19 16:58:11,189: log_options() 'quotes_width = 70'
INFO: 2021-07-19 16:58:11,189: log_options() 'safe_mode = False'
INFO: 2021-07-19 16:58:11,189: log_options() 'slideshow_custom_enabled = False'
INFO: 2021-07-19 16:58:11,189: log_options() 'slideshow_custom_folder = /home/ravanla/Pictures'
INFO: 2021-07-19 16:58:11,189: log_options() 'slideshow_downloads_enabled = False'
INFO: 2021-07-19 16:58:11,189: log_options() 'slideshow_fade = 0.4'
INFO: 2021-07-19 16:58:11,189: log_options() 'slideshow_favorites_enabled = True'
INFO: 2021-07-19 16:58:11,189: log_options() 'slideshow_mode = Fullscreen'
INFO: 2021-07-19 16:58:11,189: log_options() 'slideshow_monitor = All'
INFO: 2021-07-19 16:58:11,189: log_options() 'slideshow_pan = 0.05'
INFO: 2021-07-19 16:58:11,189: log_options() 'slideshow_seconds = 6.0'
INFO: 2021-07-19 16:58:11,190: log_options() 'slideshow_sort_order = Random'
INFO: 2021-07-19 16:58:11,190: log_options() 'slideshow_sources_enabled = True'
INFO: 2021-07-19 16:58:11,190: log_options() 'slideshow_zoom = 0.2'
INFO: 2021-07-19 16:58:11,190: log_options() 'smart_enabled = False'
INFO: 2021-07-19 16:58:11,190: log_options() 'smart_notice_shown = False'
INFO: 2021-07-19 16:58:11,190: log_options() 'smart_register_shown = False'
INFO: 2021-07-19 16:58:11,190: log_options() 'sources = [[False, 'favorites', 'The Favorites folder'], [False, 'fetched', 'The Fetched folder'], [False, 'folder', '/usr/share/backgrounds'], [False, 'flickr', 'user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'], [False, 'apod', "NASA's Astronomy Picture of the Day"], [False, 'bing', 'Bing Photo of the Day'], [False, 'earthview', 'Google Earth View Wallpapers'], [False, 'unsplash', 'High-resolution photos from Unsplash.com'], [True, 'folder', '/home/ravanla/Pictures/i3lock'], [True, 'folder', '/home/ravanla/Pictures/Move_From_Windows']]'
INFO: 2021-07-19 16:58:11,190: log_options() 'stats_enabled = True'
INFO: 2021-07-19 16:58:11,190: log_options() 'stats_notice_shown = False'
INFO: 2021-07-19 16:58:11,190: log_options() 'sync_enabled = True'
INFO: 2021-07-19 16:58:11,190: log_options() 'use_landscape_enabled = True'
INFO: 2021-07-19 16:58:11,190: reload_config() 'No need to clear prepared queue'
INFO: 2021-07-19 16:58:11,190: update_indicator() 'Setting file info to: /home/ravanla/Pictures/Move_From_Windows/download.jpg'
INFO: 2021-07-19 16:58:11,194: load_last_change_time() 'Change interval < 6 hours, ignore persisted last_change_time, wait initially the whole interval: 300'
INFO: 2021-07-19 16:58:11,194: update_indicator() 'Setting file info to: /home/ravanla/Pictures/Move_From_Windows/download.jpg'
INFO: 2021-07-19 16:58:11,195: regular_change_thread() 'regular_change thread running'
INFO: 2021-07-19 16:58:11,195: prepare_thread() 'Prepare thread running'
INFO: 2021-07-19 16:58:11,196: prepare_thread() 'Prepared buffer contains 0 images'
INFO: 2021-07-19 16:58:11,196: prepare_thread() 'Preparing some images'
INFO: 2021-07-19 16:58:11,195: regular_change_thread() 'regular_change: waiting till user resumes'
INFO: 2021-07-19 16:58:11,256: prepare_thread() 'After search prepared buffer contains 33 images'
INFO: 2021-07-19 16:58:11,297: do_set_wp() 'Calling do_set_wp with /home/ravanla/Pictures/Move_From_Windows/download.jpg, time: 1626685091.2970366'
INFO: 2021-07-19 16:58:11,325: update_indicator() 'Setting file info to: /home/ravanla/Pictures/Move_From_Windows/download.jpg'
INFO: 2021-07-19 16:58:11,520: update_indicator_icon() 'Creating indicator'
WARNING: 2021-07-19 16:58:11,537: create_menu() 'Variety Slideshow is not installed. This is an optional extension adding pan-and-zoom slideshows to Variety: see https://github.com/peterlevi/variety-slideshow for details'
INFO: 2021-07-19 16:58:11,538: create_indicator() 'indicator backend: AppIndicator3'
INFO: 2021-07-19 16:58:11,575: set_from_theme_icon() 'Showing indicator icon variety-indicator-dark from GTK theme'
INFO: 2021-07-19 16:58:13,149: reload() 'Reloading preferences dialog'
INFO: 2021-07-19 16:58:13,262: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2021-07-19 16:58:31,216: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2021-07-19 16:58:40,350: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1303, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1252, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1012, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 952, in send
    self.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fe86844d460>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe86844d460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1086, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 644, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe86844d460>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
INFO: 2021-07-19 16:59:10,383: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2021-07-19 16:59:15,417: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1303, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1252, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1012, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 952, in send
    self.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fe86844dcd0>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe86844dcd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1086, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 644, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe86844dcd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
INFO: 2021-07-19 16:59:45,446: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2021-07-19 16:59:50,457: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1303, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1252, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1012, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 952, in send
    self.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fe86844d580>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe86844d580>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1086, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 644, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe86844d580>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
INFO: 2021-07-19 17:00:20,474: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2021-07-19 17:00:25,483: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1303, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1252, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1012, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 952, in send
    self.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fe854c53520>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe854c53520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1086, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 644, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe854c53520>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
INFO: 2021-07-19 17:00:55,513: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2021-07-19 17:01:00,523: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1303, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1252, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1012, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 952, in send
    self.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fe854c53d30>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe854c53d30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/variety/VarietyWindow.py", line 1086, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 644, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.9/site-packages/variety/Util.py", line 614, in request
    r = requests.request(
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe854c53d30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
INFO: 2021-07-19 17:02:38,377: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-07-19 17:02:38,378: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-07-19 17:02:38,387: update_indicator() 'Setting file info to: /home/ravanla/Pictures/Move_From_Windows/download.jpg'
INFO: 2021-07-19 17:02:38,390: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-07-19 17:02:41,830: set_wallpaper() 'Calling set_wallpaper with /home/ravanla/Pictures/i3lock/blackcat.jpg'
INFO: 2021-07-19 17:02:41,831: do_set_wp() 'Calling do_set_wp with /home/ravanla/Pictures/i3lock/blackcat.jpg, time: 1626685361.8312953'
INFO: 2021-07-19 17:02:41,855: update_indicator() 'Setting file info to: /home/ravanla/Pictures/i3lock/blackcat.jpg'
INFO: 2021-07-19 17:02:41,858: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2021-07-19 17:02:43,999: update_indicator() 'Setting file info to: /home/ravanla/Pictures/i3lock/blackcat.jpg'
INFO: 2021-07-19 17:02:43,999: list_files() 'More than 1 files in the folders, stop listing'
